APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:aN9w9FM2rAg9EsrL+9gdn/XGefOjPg+IGtYORnZO1Lo=
APP_DEBUG=true
APP_URL=https://turtlecore.com/email

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE="u408477171_email"
DB_USERNAME="u408477171_email"
DB_PASSWORD="U408477171_email"

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DRIVER=local
QUEUE_CONNECTION=database
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

AUTH_NAME = null
AUTH_EMAIL = null
AUTH_PASSWORD = null

MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME="${AUTH_EMAIL}"
MAIL_PASSWORD="${AUTH_PASSWORD}"
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS="${AUTH_EMAIL}"
MAIL_FROM_NAME="${AUTH_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
